In [47]:
import numpy as np

In [48]:
horizontal_vector = np.array([5,0])
vertical_vector = np.array([[5],[0]])

# horizontal_vector to vertical_vector

# horizontal_vector.shape = (2,1)
# horizontal_vector

new_vertical_vector1 = horizontal_vector.reshape(2,1)

new_vertical_vector2 = np.vstack(horizontal_vector)

new_vertical_vector3 = horizontal_vector[:, None]

new_vertical_vector4 = horizontal_vector[:, np.newaxis]

new_vertical_vector1, new_vertical_vector2, new_vertical_vector3, new_vertical_vector4, np.newaxis==None

(array([[5],
        [0]]),
 array([[5],
        [0]]),
 array([[5],
        [0]]),
 array([[5],
        [0]]),
 True)